<?php

namespace ActiviteBundle\Repository;

/**
 * InscriptionActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionActiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
