<?php

namespace RestaurantBundle\Repository;

/**
 * AARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AARepository extends \Doctrine\ORM\EntityRepository
{

    public function countInscri($i){
        $query=$this->getEntityManager()->createQuery("SELECT COUNT( c) FROM RestaurantBundle:InscriptionRepas c WHERE c.repas='$i'");
        return $query->getResult();
        //SELECT COUNT(*) FROM RestaurantBundle:InscriptionRepas WHERE repas='$i'
    }
}
