<?php

namespace RestaurantBundle\Repository;

/**
 * AARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AARepository extends \Doctrine\ORM\EntityRepository
{
}
