<?php

namespace PreinscriptionBundle\Repository;

/**
 * EnfantPreInscritRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantPreInscritRepository extends \Doctrine\ORM\EntityRepository
{
}
