<?php

namespace PreinscriptionBundle\Repository;

/**
 * InscriptionParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionParentRepository extends \Doctrine\ORM\EntityRepository
{
}
