<?php

namespace PreinscriptionBundle\Repository;

/**
 * ParentPreInscritRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentPreInscritRepository extends \Doctrine\ORM\EntityRepository
{
}
