<?php

namespace BibliothequeBundle\Repository;

/**
 * CDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CDRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCDByDate(){
        return $this->createQueryBuilder('cd')
            ->where('cd.endDateEmprunt < CURRENT_DATE()')
            ->getQuery()->getResult();
    }
}
