<?php

namespace BibliothequeBundle\Repository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLivreByDate(){
        return $this->createQueryBuilder('livre')
            ->where('livre.endDateEmprunt < CURRENT_DATE()')
           ->getQuery()->getResult();
    }

}
