evenement_evenement:
    resource: "@EvenementBundle/Resources/config/routing/evenement.yml"
    prefix:   /evenement

evenement_homepage:
    path:     /
    defaults: { _controller: EvenementBundle:Default:index }
