preinscription:
    resource: "@PreinscriptionBundle/Resources/config/routing.yml"
    prefix:   /preinscription

restaurant_plat:
    resource: "@RestaurantBundle/Controller/PlatController.php"
    type:     annotation

activite:
    resource: "@ActiviteBundle/Resources/config/routing.yml"
    prefix:   /activite

evaluation:
    resource: "@EvaluationBundle/Resources/config/routing.yml"
    prefix:   /evaluation

paiement:
    resource: "@PaiementBundle/Resources/config/routing.yml"
    prefix:   /payer

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"

restaurant:
    resource: "@RestaurantBundle/Resources/config/routing.yml"
    prefix:   /resto

bibliotheque:
    resource: "@BibliothequeBundle/Resources/config/routing.yml"
    prefix:   /biblio

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /event

rh:
    resource: "@RHBundle/Resources/config/routing.yml"
    prefix:   /RH



app_index:
  path:     /
  defaults: { _controller: "AppBundle:Default:index" }
  methods:  GET

app_admin:
  path:     /admin
  defaults: { _controller: "AppBundle:Default:admin" }
  methods:  GET

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

pdfexample:
  path:     /pdf/{id}
  defaults: { _controller: "AppBundle:Default:pdf" }
  methods:  [GET,POST]

app_index_parent:
  path:     /indexparent
  defaults: { _controller: "AppBundle:Default:indexparent" }

toiba_fullcalendar:
  resource: "@FullCalendarBundle/Resources/config/routing.yaml"
pay_form:
    path: /paypal/{montant}
    defaults: { _controller: "PaiementBundle:Default:pay" }
    methods: [GET,POST]
show_facture:
    path: /facture
    defaults: { _controller: "PaiementBundle:Default:show_facture" }
log_cont:
  path:     /verif
  defaults: { _controller: "AppBundle:Default:log" }
  methods:  GET
admin_home:
  path:     /Dashbord
  defaults: { _controller: "AppBundle:Default:admin_home" }
  methods:  GET
parent_home:
    path:   /ense
    defaults: { _controller: "AppBundle:Default:parent_home" }
    methods:  GET
enseignant_home:
    path:   /enseignat
    defaults: { _controller: "AppBundle:Default:enseignant_home" }
    methods:  GET
