security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ENSEIGNANT: ROLE_ENSEIGNANT
        ROLE_PARENT: ROLE_PARENT
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle

                use_referer: true
                default_target_path: /verif
                csrf_token_generator: security.csrf.token_manager


            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/RH, role: ROLE_USER   }
        - { path: ^/profile, role: ROLE_PARENT  }
        - { path: ^/, role: ROLE_ENSEIGNANT  }



#Admin  p@ssword
#Hassen 123654