<?php

namespace PaiementBundle\Repository;

/**
 * ordersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ordersRepository extends \Doctrine\ORM\EntityRepository
{
}
