enseignant_index:
    path:     /
    defaults: { _controller: "RHBundle:Enseignant:index" }
    methods:  [GET, POST]

enseignant_show:
    path:     /{id}/show
    defaults: { _controller: "RHBundle:Enseignant:show" }
    methods:  GET

enseignant_new:
    path:     /new
    defaults: { _controller: "RHBundle:Enseignant:new" }
    methods:  [GET, POST]

enseignant_edit:
    path:     /{id}/edit
    defaults: { _controller: "RHBundle:Enseignant:edit" }
    methods:  [GET, POST]

enseignant_delete:
    path:     /{id}/delete
    defaults: { _controller: "RHBundle:Enseignant:delete" }
    methods:  DELETE
